import Foundation


struct ConstantMap{
	static let usc_map = [
		"PSA":
			["id": "191", "name": "PARKING STRUCTURE A", "address": "LOT 33-3667 MCCLINTOCK AVE. LOS ANGELES CA 90089"],
		"BLA":
			["id": "649", "name": "BOATHOUSE-PORT OF LOS ANGELES-ATHLETICS WOMENS ROWING", "address": "BERTH 94 PORT OF L.A. SAN PEDRO CA 90733"],
		"CRW":
			["id": "138", "name": "CREW HOUSE", "address": "BERTH 194 YACHT ST. WILMINGTON CA 90744"],
		"CST":
			["id": "246", "name": "CAD SERVICES TRAILER", "address": "BERTH 194 YACHT ST. WILMINGTON CA 90744"],
		"RIM":
			["id": "785", "name": "REEF MESA RIM, INC. BUILDING", "address": "9860 MESA RIM ROAD SAN DIEGO CA 92121"],
		"TAP":
			["id": "180", "name": "TROYLAND APARTMENTS", "address": "955-59 WEST ADAMS BLVD. LOS ANGELES CA 90007"],
		"MCT":
			["id": "300", "name": "MCCULLOCH TOWNHOMES", "address": "953 W. 30TH ST. LOS ANGELES CA 90007"],
		"JEF":
			["id": "129", "name": "JEFFERSON BUILDING", "address": "950 WEST JEFFERSON BLVD. LOS ANGELES CA 90089"],
		"UPV":
			["id": "401", "name": "UNIVERSITY PARK TELEPHONE VAULT", "address": "950 DOWNEY WAY LOS ANGELES CA 90089"],
		"SAL":
			["id": "78", "name": "HENRY SALVATORI COMPUTER SCIENCE CENTER", "address": "941 BLOOM WALK LOS ANGELES CA 90089"],
		"JMC":
			["id": "321", "name": "JOHN MCKAY CENTER", "address": "940 W. 35TH STREET LOS ANGELES CA 90089"],
		"EVA":
			["id": "404", "name": "UNIVERSITY PARK ELECTRICAL VAULT A", "address": "936 WEST 36TH ST LOS ANGELES CA 90089"],
		"SCC":
			["id": "313", "name": "SCHOOL OF CINEMATIC ARTS-BUILDING C", "address": "935 W. 35TH STREET LOS ANGELES CA 90089"],
		"SCB":
			["id": "312", "name": "SCHOOL OF CINEMATIC ARTS-BUILDING B", "address": "930 W.34TH STREET LOS ANGELES CA 90089"],
		"UVS":
			["id": "346", "name": "UNIVERSITY VILLAGE SIX", "address": "929 W. JEFFERSON BLVD. LOS ANGELES CA 90007"],
		"DEN":
			["id": "64", "name": "EILEEN & KENNETH T. NORRIS DENTAL SCIENCE CENTER", "address": "925 WEST 34TH ST. LOS ANGELES CA 90089"],
		"TDF":
			["id": "801", "name": "TEMPORARY DINING FACILITY", "address": "925 W. DOWNEY WAY LOS ANGELES CA 90089"],
		"HED":
			["id": "72", "name": "HEDCO PETROLEUM & CHEMICAL ENGINEERING BUILDING", "address": "925 BLOOM WALK LOS ANGELES CA 90089"],
		"PCE":
			["id": "121", "name": "JERRY & NANCY NEELY PETROLEUM & CHEMICAL ENGINEERING BUILDING", "address": "923 BLOOM WALK LOS ANGELES CA 90089"],
		"CLN":
			["id": "225", "name": "EMPTY LOT FORMERLY COLONIAL APTS", "address": "921 WEST 30TH ST. LOS ANGELES CA 90007"],
		"TSH":
			["id": "319", "name": "THIRTIETH STREET HOUSE", "address": "921 W. 30TH STREET LOS ANGELES CA 90007"],
		"PRB":
			["id": "139", "name": "PARKSIDE RESIDENTIAL BUILDING", "address": "920 WEST 37TH PLACE LOS ANGELES CA 90089"],
		"DCF":
			["id": "156", "name": "DELTA CHI FRATERNITY", "address": "920 WEST 28TH ST. LOS ANGELES CA 90007"],
		"BHE":
			["id": "23", "name": "BIEGLER HALL OF ENGINEERING", "address": "920 DOWNEY WAY LOS ANGELES CA 90089"],
		"SSC":
			["id": "48", "name": "FRANK R. SEAVER SCIENCE CENTER", "address": "920 BLOOM WALK LOS ANGELES CA 90089"],
		"SCX":
			["id": "314", "name": "SCHOOL OF CINEMATIC ARTS-BUILDING D", "address": "915 W. 35TH STREET LOS ANGELES CA 90089"],
		"EVB":
			["id": "405", "name": "UNIVERSITY PARK ELECTRICAL VAULT B", "address": "910 WEST JEFFERSON BLVD. LOS ANGELES CA 90089"],
		"SSL":
			["id": "49", "name": "SEAVER SCIENCE LIBRARY", "address": "910 BLOOM WALK LOS ANGELES CA 90089"],
		"ONE":
			["id": "158", "name": "ONE INSTITUTE", "address": "909 WEST ADAMS BLVD LOS ANGELES CA 90007"],
		"SCE":
			["id": "315", "name": "SCHOOL OF CINEMATIC ARTS-BUILDING E", "address": "905 W. 35TH STREET LOS ANGELES CA 90089"],
		"AEP":
			["id": "157", "name": "ALPHA EPSILON PI", "address": "904 WEST 28TH ST. LOS ANGELES CA 90007"],
		"WMB":
			["id": "728", "name": "WILSHIRE MEDICAL BUILDING", "address": "9033 WILSHIRE #300, #500 BEVERLY HILLS CA 90211"],
		"SCA":
			["id": "294", "name": "SCHOOL OF CINEMATIC ARTS", "address": "900 W. 34TH STREET LOS ANGELES CA 90089"],
		"GFM":
			["id": "713", "name": "GLOBAL FIVE MANAGEMENT-KSOM", "address": "8900 WILSHIRE BLVD. BEVERLY HILLS CA 90211"],
		"RTA":
			["id": "174", "name": "REGAL TROJAN APARTMENTS", "address": "870 WEST ADAMS BLVD. LOS ANGELES CA 90007"],
		"CRA":
			["id": "672", "name": "LOS ANGELES CAREGIVER RESOURCE CENTER-LANCASTER", "address": "858 WEST JACKSON STREET LANCASTER CA 93534"],
		"RRB":
			["id": "119", "name": "ROBERT GLEN RAPP ENGINEERING RESEARCH BUILDING", "address": "854 DOWNEY WAY LOS ANGELES CA 90089"],
		"HSH":
			["id": "105", "name": "HAZEL & STANLEY HALL FINANCIAL SERVICES BUILDING", "address": "851 DOWNEY WAY LOS ANGELES CA 90089"],
		"WWB":
			["id": "661", "name": "WEST WASHINGTON BLVD", "address": "850 WEST WASHINGTON BLVD LOS ANGELES CA 90008"],
		"MBC":
			["id": "260", "name": "MACDONALD BECKET CENTER", "address": "850 W. BLOOM WALK LOS ANGELES CA 90089"],
		"WAH":
			["id": "29", "name": "RAY & NADINE WATT HALL OF ARCHITECTURE & FINE ARTS", "address": "850 BLOOM WALK LOS ANGELES CA 90089"],
		"KDC":
			["id": "352", "name": "GLORYA KAUFMAN INTERNATIONAL DANCE CENTER", "address": "849 W. 34TH STREET LOS ANGELES CA 90089"],
		"OSP":
			["id": "636", "name": "OUR SAVIOR PARISH & USC CARUSO CATHOLIC CENTER", "address": "844 W. 32ND STREET LOS ANGELES CA 90007"],
		"MUS":
			["id": "85", "name": "ALBERT S. RAUBENHEIMER MUSIC FACULTY MEMORIAL BUILDING", "address": "840 WEST 34TH ST. LOS ANGELES CA 90089"],
		"LJS":
			["id": "40.1", "name": "LAIRD J. STABLER MEMORIAL HALL", "address": "840 DOWNEY WAY LOS ANGELES CA 90089"],
		"BKS":
			["id": "254", "name": "PERTUSATI UNIVERSITY BOOKSTORE", "address": "840 CHILDS WAY LOS ANGELES CA 90089"],
		"NLC":
			["id": "677", "name": "NORMAN LEAR CENTER - ANNENBERG SCHOOL OF COMMUNICATION", "address": "8383 WILSHIRE BLVD. #652 LOS ANGELES CA 90007"],
		"STO":
			["id": "114", "name": "STONIER HALL", "address": "837 DOWNEY WAY LOS ANGELES CA 90089"],
		"LHI":
			["id": "166", "name": "DONALD P. & KATHERINE B. LOKER HYDROCARBON INSTITUTE", "address": "837 BLOOM WALK LOS ANGELES CA 90089"],
		"URC":
			["id": "75", "name": "UNIVERSITY RELIGIOUS CENTER", "address": "835 WEST 34TH ST. LOS ANGELES CA 90089"],
		"UVV":
			["id": "347", "name": "UNIVERSITY VILLAGE SEVEN", "address": "835 W. JEFFERSON BLVD. LOS ANGELES CA 90007"],
		"SHS":
			["id": "134", "name": "JOHN STAUFFER HALL OF SCIENCE", "address": "835 BLOOM WALK LOS ANGELES CA 90089"],
		"SLH":
			["id": "135", "name": "JOHN STAUFFER SCIENCE LECTURE HALL", "address": "831 BLOOM WALK LOS ANGELES CA 90089"],
		"RHM":
			["id": "83", "name": "VIRGINIA RAMO HALL OF MUSIC", "address": "830 WEST 34TH ST. LOS ANGELES CA 90089"],
		"ACX":
			["id": "148.1", "name": "AHMANSON CENTER FOR BIOLOGICAL RESEARCH ANIMAL SECTION", "address": "825 BLOOM WALK LOS ANGELES CA 90089"],
		"ACB":
			["id": "148", "name": "AHMANSON CENTER FOR BIOLOGICAL RESEARCH", "address": "825 BLOOM WALK LOS ANGELES CA 90089"],
		"HAR":
			["id": "38", "name": "MAY ORMEROD HARRIS HALL, QUINN WING & FISHER GALLERY", "address": "823-29 EXPOSITION BLVD. LOS ANGELES CA 90089"],
		"CLH":
			["id": "127", "name": "COLLEGE HOUSE", "address": "823 W. 34TH STREET LOS ANGELES CA 90089"],
		"BMH":
			["id": "144", "name": "MRS. WILLIS H. BOOTH FERRIS REHEARSAL HALL", "address": "820 WEST 34TH ST. LOS ANGELES CA 90089"],
		"UUC":
			["id": "623", "name": "UNITED UNIVERSITY CHURCH", "address": "817 WEST 34TH STREET LOS ANGELES CA 90089"],
		"CEM":
			["id": "10", "name": "CENTER FOR ELECTRON MICROSCOPY AND MICROANALYSIS", "address": "814 WEST BLOOM WALK LOS ANGELES CA 90089"],
		"THB":
			["id": "665", "name": "TOMAHAWK BUILDING", "address": "812 SPRING STREET LOS ANGELES CA 90014"],
		"FAB":
			["id": "685", "name": "FINE ARTS BUILDING-DOWNTOWN", "address": "811 W. 7TH SREET LOS ANGELES CA 90017"],
		"OCW":
			["id": "40", "name": "HAROLD E. AND LILLIAN M. MOULTON ORGANIC CHEMISTRY WING", "address": "810 DOWNEY WAY LOS ANGELES CA 90089"],
		"AHN":
			["id": "14", "name": "DOSAN AHN CHANG HO FAMILY HOUSE", "address": "809 W. 34TH STREEET LOS ANGELES CA 90089"],
		"JEP":
			["id": "47", "name": "JOINT EDUCATIONAL PROJECT HOUSE", "address": "801 WEST 34TH ST. LOS ANGELES CA 90089"],
		"MFT":
			["id": "710", "name": "MANI FIGUEROA TOWER", "address": "801 S. FIGUEROA STREET LOS ANGELES CA 90017"],
		"MPI":
			["id": "641", "name": "MULTIPOINT INTERNATIONAL-ISD CO-LOCATION SITE FOR EQUIPMENT", "address": "800 S. HOPE STREET LOS ANGELES CA 90007"],
		"EGG":
			["id": "261", "name": "EGG COMPANY II", "address": "746 WEST ADAMS LOS ANGELES CA 90007"],
		"ECT":
			["id": "52", "name": "EARLY CHILDHOOD TRAINING CENTER", "address": "741 WEST 27TH ST. LOS ANGELES CA 90007"],
		"CNG":
			["id": "232", "name": "CARDINAL 'N' GOLD", "address": "737 WEST 30TH ST. LOS ANGELES CA 90007"],
		"KER":
			["id": "42", "name": "KERCKHOFF HALL", "address": "734 WEST ADAMS BLVD. LOS ANGELES CA 90007"],
		"KCH":
			["id": "97", "name": "KERCKHOFF CARRIAGE HOUSE", "address": "734 WEST ADAMS BLVD. LOS ANGELES CA 90007"],
		"ADX":
			["id": "311", "name": "ALPHA DELTA CHI HOUSE", "address": "725-731 W. 32ND STREET LOS ANGELES CA 90007"],
		"LCA":
			["id": "151", "name": "LAMBDA CHI ALPHA", "address": "720 WEST 28TH ST. LOS ANGELES CA 90007"],
		"COR":
			["id": "718", "name": "CORSICA-SERVICED BY ITS", "address": "715 W. 32ND STREET LOS ANGELES CA 90007"],
		"ANH":
			["id": "185", "name": "ANNENBERG HOUSE", "address": "711 WEST 27TH ST. LOS ANGELES CA 90007"],
		"KSH":
			["id": "154", "name": "UNIVERSITY CLUB AT KING STOOPS HALL", "address": "705 W. 34TH STREET LOS ANGELES CA 90089"],
		"HAS":
			["id": "719", "name": "HABITAT SOO ZEE-SERVICED BY ITS", "address": "701 W, 32ND STREET LOS ANGELES CA 90007"],
		"MSE":
			["id": "705", "name": "MARKET SQUARE EAST TOWER", "address": "701 PENNSYLVANIA AVE. NW WASHINGTON DC 20004"],
		"HOH":
			["id": "142", "name": "H. LESLIE HOFFMAN HALL OF BUSINESS ADMINISTRATION", "address": "701 EXPOSITION BLVD. LOS ANGELES CA 90089"],
		"JHH":
			["id": "91", "name": "JOHN HUBBARD HALL (FORMERLY SAS)", "address": "700 CHILDS WAY LOS ANGELES CA 90089"],
		"LAW":
			["id": "7", "name": "ELVON & MABEL MUSICK LAW BUILDING (CENTER)", "address": "699 EXPOSITION BLVD. LOS ANGELES CA 90089"],
		"MRF":
			["id": "41", "name": "MONTGOMERY ROSS FISHER BUILDING (SCHOOL OF SOCIAL WORK)", "address": "669 WEST 34TH ST. LOS ANGELES CA 90089"],
		"GSS":
			["id": "648", "name": "GIBBONS STREET STORAGE (SAN ANTONIO WINERY)-KSOM STORAGE", "address": "667 GIBBONS STREET LOS ANGELES CA 90031"],
		"TGF":
			["id": "112", "name": "TOWN & GOWN", "address": "665 EXPOSITION BLVD. LOS ANGELES CA 90089"],
		"SHR":
			["id": "637", "name": "SHRINE AUDITORIUM", "address": "661 WEST JEFFERSON BLVD. LOS ANGELES CA 90007"],
		"PWE":
			["id": "902", "name": "PARDEE WAY ENTRANCE-GATE #2", "address": "661 W. EXPOSISTION BLVD LOS ANGELES CA 90089"],
		"SWC":
			["id": "283", "name": "SOCIAL WORK CENTER", "address": "655 W. 34TH STREET LOS ANGELES CA 90089"],
		"LVL":
			["id": "257", "name": "THOMAS & DOROTHY LEAVEY LIBRARY", "address": "650 WEST MCCARTHY WAY LOS ANGELES CA 90089"],
		"RGL":
			["id": "262", "name": "RALPH AND GOLDY LEWIS HALL", "address": "650 CHILDS WAY LOS ANGELES CA 90089"],
		"WJC":
			["id": "697", "name": "WESTERN JUSTICE CENTER", "address": "65 S. GRAND AVE. PASADENA CA 91105"],
		"PSD":
			["id": "162", "name": "PARKING STRUCTURE D", "address": "649 WEST 34TH ST. LOS ANGELES CA 90089"],
		"PSV":
			["id": "402", "name": "PARKING STRUCTURE D TELEPHONE VAULT", "address": "649 W. 34TH STREET LOS ANGELES CA 90089"],
		"SHP":
			["id": "355", "name": "SHRINE PARKING STRUCTURE", "address": "645 W. JEFFERSON BLVD. LOS ANGELES CA 90007"],
		"FAC":
			["id": "116", "name": "FACULTY CENTER-UNIVERSITY CLUB", "address": "645 EXPOSITION BLVD. LOS ANGELES CA 90089"],
		"BSR":
			["id": "88", "name": "CECELE & MICHAEL BIRNKRANT RESIDENCE HALL", "address": "642 WEST 34TH ST. LOS ANGELES CA 90089"],
		"SCS":
			["id": "356", "name": "USC SCHOOL OF CINEMATIC ARTS STATION", "address": "639 WEST 32ND STREET LOS ANGELES CA 90007"],
		"GSM":
			["id": "627", "name": "GOOD SAMARITAN HOSPITAL", "address": "637 LUCAS STREET LOS ANGELES CA 90017"],
		"EVK":
			["id": "99", "name": "ELISABETH VON KLEINSMID MEMORIAL RESIDENCE HALL", "address": "635 WEST MCCARTHY WAY LOS ANGELES CA 90089"],
		"VPD":
			["id": "331", "name": "VERNA & PETER DAUTERIVE HALL", "address": "635 DOWNEY WAY LOS ANGELES CA 90089"],
		"ALM":
			["id": "46", "name": "WIDNEY ALUMNI HOUSE", "address": "635 CHILDS WAY LOS ANGELES CA 90089"],
		"HRH":
			["id": "99.1", "name": "MAY ORMEROD HARRIS RESIDENCE HALL", "address": "634 WEST 34TH ST. LOS ANGELES CA 90089"],
		"SAI":
			["id": "195", "name": "STARDUST APARTMENTS", "address": "634 WEST 27TH ST. LOS ANGELES CA 90007"],
		"DXM":
			["id": "94", "name": "DAVID X. MARKS RESIDENCE HALL", "address": "631 CHILDS WAY LOS ANGELES CA 90089"],
		"TSS":
			["id": "193", "name": "THEATRE SCENE SHOP", "address": "624 WEST 32ND ST LOS ANGELES CA 90007"],
		"PLB":
			["id": "904", "name": "PARKING LOT B ENTRANCE-GATE #4", "address": "622 W. 34TH STREET LOS ANGELES CA 90089"],
		"SGA":
			["id": "242", "name": "SEVEN GABLES APARTMENTS", "address": "620-626 WEST 30TH ST. LOS ANGELES CA 90007"],
		"PSX":
			["id": "133", "name": "PARKING STRUCTURE C", "address": "620 WEST MCCARTHY WAY LOS ANGELES CA 90089"],
		"TFE":
			["id": "903", "name": "THIRTY-FIFTH STREET ENTRANCE-GATE#3", "address": "620 W. 35TH STREET LOS ANGELES CA 90089"],
		"URH":
			["id": "100.1", "name": "UNIVERSITY RESIDENCE HALL", "address": "616 WEST 34TH ST. LOS ANGELES CA 90089"],
		"COL":
			["id": "100", "name": "COLLEGE RESIDENCE HALL", "address": "615 WEST MCCARTHY WAY LOS ANGELES CA 90089"],
		"TRO":
			["id": "120", "name": "TROJAN RESIDENCE HALL", "address": "615 CHILDS WAY LOS ANGELES CA 90089"],
		"PTD":
			["id": "189", "name": "MARIANNE & J.DOUGLAS PARDEE TOWER", "address": "614 HELLMAN WAY LOS ANGELES CA 90089"],
		"DMT":
			["id": "149", "name": "DAVID X. MARKS TOWER", "address": "612 HELLMAN WAY LOS ANGELES CA 90089"],
		"JKP":
			["id": "263", "name": "JANE HOFFMAN POPOVICH & J. KRISTOFFER POPOVICH HALL", "address": "611 EXPOSITION BLVD. LOS ANGELES CA 90089"],
		"JFF":
			["id": "336", "name": "JILL & FRANK FERTITTA HALL", "address": "610 CHILDS WAY LOS ANGELES CA 90089"],
		"CBB":
			["id": "680", "name": "CENTURY BOULEVARD BUILDING-VITERBI CONTINUING EDUCATION PROGRAM", "address": "6033 CENTURY BLVD., #920 LOS ANGELES CA 90045"],
		"WCC":
			["id": "712", "name": "WESTSIDE JEWISH COMMUNITY CTR.-SCHOOL OF FINE ARTS", "address": "5870 OLYMPIC BLVD. LOS ANGELES CA 90036"],
		"APP":
			["id": "699", "name": "AIRPORT PACIFIC PROPERTIES", "address": "5318-5320 MC CONNELL AVE. LOS ANGELES CA 90066"],
		"FML":
			["id": "130", "name": "FEUCHTWANGER MEMORIAL LIBRARY", "address": "520 PASEO MIRAMAR PACIFIC PALISADES CA 90272"],
		"MLP":
			["id": "682", "name": "MANULIFE PLAZA (KUSC)", "address": "515 S. FIGUEROA ST LOS ANGELES CA 90071"],
		"MVB":
			["id": "691", "name": "MOUNTAIN VIEW BUILDING", "address": "480 SAN ANTONIO RD. MOUNTAIN VIEW CA 94040"],
		"ISI":
			["id": "616", "name": "INFORMATION SCIENCE INSTITUTE", "address": "4676 ADMIRALTY WAY MARINA DEL REY CA 90292"],
		"MTR":
			["id": "696", "name": "MARINA TOWERS RETAIL", "address": "4666 ADMIRALTY WAY MARINA DEL REY CA 90292"],
		"CHL":
			["id": "626", "name": "CHILDRENS HOSPITAL", "address": "4640 WEST SUNSET BLVD LOS ANGELES CA 90027"],
		"MTN":
			["id": "695", "name": "MARINA TOWERS NORTH", "address": "4640 ADMIRALTY WAY MARINA DEL REY CA 90292"],
		"PAM":
			["id": "339", "name": "PACIFIC ASIA MUSEUM", "address": "46 N. LOS ROBLES AVENUE PASADENA CA 91101"],
		"CGC":
			["id": "700", "name": "CITI GROUP CENTER", "address": "444 S. FLOWER STREET LOS ANGELES CA 90071"],
		"VBB":
			["id": "652", "name": "VALLEY BOULEVARD BUILDING", "address": "4351 EAST VALLEY BLVD LOS ANGELES CA 90033"],
		"FPC":
			["id": "646", "name": "USC FAMILY PRACTICE CENTER", "address": "420 W. LAS TUNAS DR. SAN GABRIEL CA 91778"],
		"VWB":
			["id": "298", "name": "VALLEY WAREHOUSE BUILDING", "address": "4121 VALLEY BLVD LOS ANGELES CA 90033"],
		"FOB":
			["id": "606", "name": "FORD OFFICE BUILDING", "address": "40365 SAND DUNE ROAD RANCHO MIRAGE CA 92270"],
		"GAH":
			["id": "196", "name": "GAMBLE HOUSE", "address": "4 WESTMORELAND PLACE PASADENA CA 91103"],
		"MTA":
			["id": "212", "name": "MT. ADA CATALINA", "address": "398 WRIGLEY RD. AVALON CA 90704"],
		"SAR":
			["id": "754", "name": "LOS ANGELES SPORTS ARENA", "address": "3939 S. FIGUEROA LOS ANGELES CA 90037"],
		"CLS":
			["id": "753", "name": "LOS ANGELES MEMORIAL COLISEUM", "address": "3911 S. FIGUEROA LOS ANGELES CA 90037"],
		"ISE":
			["id": "633", "name": "INFORMATION SCIENCE INSTITUTE EAST", "address": "3811 N. FAIRFAX ARLINGTON VA 22202"],
		"ELS":
			["id": "707", "name": "ELS INVESTMENTS, INC.", "address": "3780 12TH ST. RIVERSIDE CA 92501"],
		"DWE":
			["id": "906", "name": "DOWNEY WAY ENTRANCE-GATE #6", "address": "3771 MCCLINTOCK AVE. LOS ANGELES CA 90089"],
		"IRC":
			["id": "277", "name": "INTERNATIONALLY THEMED RESIDENTIAL COLLEGE", "address": "3771 MCCLINTOCK AVE. LOS ANGELES CA 90089"],
		"TUS":
			["id": "722", "name": "TUSCANY-SERVICED BY ITS", "address": "3760 S. FIGUEROA STREET LOS ANGELES CA 90007"],
		"EEB":
			["id": "256", "name": "HUGHES AIRCRAFT ELECTRICAL ENGINEERING CENTER", "address": "3740 MCCLINTOCK AVE LOS ANGELES CA 90089"],
		"PHE":
			["id": "27", "name": "CHARLES LEE POWELL HALL", "address": "3737 WATT WAY LOS ANGELES CA 90089"],
		"PKS":
			["id": "117", "name": "PARKSIDE APARTMENTS I", "address": "3730 MCCLINTOCK AVE. LOS ANGELES CA 90089"],
		"CUB":
			["id": "702", "name": "USC CREDIT UNION BUILDING", "address": "3720 S. FLOWER STREET LOS ANGELES CA 90089"],
		"RAN":
			["id": "153", "name": "HOFFMAN CONTRACTS RESEARCH BUILDING", "address": "3716 SOUTH HOPE STREET LOS ANGELES CA 90007"],
		"GER":
			["id": "19", "name": "ETHEL PERCY ANDRUS GERONTOLOGY CENTER", "address": "3715 MCCLINTOCK AVE. LOS ANGELES CA 90089"],
		"RTH":
			["id": "290", "name": "RONALD TUTOR HALL OF ENGINEERING", "address": "3710 MCCLINTOCK AVE. LOS ANGELES CA 90089"],
		"MHP":
			["id": "45", "name": "SEELEY WINTERSMITH MUDD MEMORIAL HALL (OF PHILOSOPHY)", "address": "3709 TROUSDALE PARKWAY LOS ANGELES CA 90089"],
		"PSO":
			["id": "164", "name": "PARKING STRUCTURE ONE", "address": "3701 FLOWER STREET LOS ANGELES CA 90089"],
		"BRI":
			["id": "8", "name": "BRIDGE MEMORIAL HALL", "address": "3670 TROUSDALE PARKWAY LOS ANGELES CA 90089"],
		"ACC":
			["id": "44", "name": "ELAINE & KENNETH LEVENTHAL SCHOOL OF ACCOUNTING", "address": "3660 TROUSDALE PARKWAY LOS ANGELES CA 90089"],
		"VHE":
			["id": "24", "name": "VIVIAN HALL OF ENGINEERING", "address": "3651 WATT WAY LOS ANGELES CA 90089"],
		"ZHS":
			["id": "74", "name": "JAMES H. ZUMBERGE HALL OF SCIENCE", "address": "3651 TROUSDALE PARKWAY LOS ANGELES CA 90089"],
		"OHE":
			["id": "145", "name": "OLIN HALL OF ENGINEERING", "address": "3650 MCCLINTOCK AVE. LOS ANGELES CA 90089"],
		"HNB":
			["id": "252", "name": "HEDCO NEUROSCIENCES BUILDING", "address": "3641 WATT WAY LOS ANGELES CA 90089"],
		"ANN":
			["id": "327", "name": "WALLIS ANNENBERG HALL", "address": "3630 WATT WAY LOS ANGELES CA 90089"],
		"DNI":
			["id": "292", "name": "DORNSIFE NEUROSCIENCE IMAGING CENTER", "address": "3620A MCCLINTOCK AVE. LOS ANGELES CA 90089"],
		"KAP":
			["id": "253", "name": "KAPRIELIAN HALL", "address": "3620 SOUTH VERMONT AVE. LOS ANGELES CA 90089"],
		"SGM":
			["id": "106", "name": "SEELEY G. MUDD BUILDING", "address": "3620 MCCLINTOCK AVE. LOS ANGELES CA 90089"],
		"AHF":
			["id": "37", "name": "ALLAN HANCOCK FOUNDATION", "address": "3616 TROUSDALE PARKWAY LOS ANGELES CA 90089"],
		"SKS":
			["id": "323", "name": "STEVEN & KATHRYN SAMPLE HALL", "address": "3607 TROUSDALE PKWY. LOS ANGELES CA 90089"],
		"TCC":
			["id": "310", "name": "RONALD TUTOR CAMPUS CENTER", "address": "3607 TROUSDALE PARKWAY LOS ANGELES CA 90089"],
		"GFS":
			["id": "169", "name": "GRACE FORD SALVATORI HALL OF LETTERS, ARTS & SCIENCES", "address": "3601 WATT WAY LOS ANGELES CA 90089"],
		"STU":
			["id": "89", "name": "GWYNN WILSON STUDENT UNION", "address": "3601 TROUSDALE PARKWAY LOS ANGELES CA 90089"],
		"TYL":
			["id": "80", "name": "JOHN & ALICE TYLER BUILDING", "address": "3601 SOUTH FLOWER ST. LOS ANGELES CA 90007"],
		"WWG":
			["id": "901", "name": "WATT WAY ENTRANCE-GATE #1", "address": "3600 W. EXPOSITION BLVD. LOS ANGELES CA 90089"],
		"PED":
			["id": "65", "name": "PHYSICAL EDUCATION BUILDING", "address": "3560 WATT WAY LOS ANGELES CA 90089"],
		"ADM":
			["id": "1", "name": "GEORGE FINLEY BOVARD ADMINISTRATION BUILDING & KENNETH NORRIS JR. AUDITORIUM", "address": "3551 TROUSDALE PARKWAY LOS ANGELES CA 90089"],
		"PPL":
			["id": "683", "name": "PARAMOUNT PLAZA", "address": "3550 WILSHIRE BLVD. LOS ANGELES CA 90007"],
		"DML":
			["id": "18", "name": "EDWARD L. DOHENY JR. MEMORIAL LIBRARY", "address": "3550 TROUSDALE PARKWAY LOS ANGELES CA 90089"],
		"LTS":
			["id": "276", "name": "KATHERINE B. LOKER TRACK STADIUM", "address": "3550 MCCLINTOCK AVE. LOS ANGELES CA 90089"],
		"RMH":
			["id": "271", "name": "RADISSON MIDCITY HOTEL", "address": "3540 S. FIGUEROA ST. LOS ANGELES CA 90007"],
		"FIG":
			["id": "126", "name": "FIGUEROA BUILDING", "address": "3535 SOUTH FIGUEROA ST. LOS ANGELES CA 90089"],
		"EPS":
			["id": "233", "name": "EXPOSITION BLVD. PARKING STRUCTURE", "address": "3533 S. FLOWER STREET LOS ANGELES CA 90089"],
		"CFH":
			["id": "230", "name": "DEAN BARTLETT CROMWELL FIELD HOUSE", "address": "3525 WATT WAY LOS ANGELES CA 90089"],
		"TES":
			["id": "407", "name": "THERMAL ENERGY STORAGE TANK", "address": "3525 WATT WAY LOS ANGELES CA 90089"],
		"CFX":
			["id": "507", "name": "DEAN BARTLETT CROMWELL FIELD", "address": "3525 WATT WAY LOS ANGELES CA 90089"],
		"RHR":
			["id": "272", "name": "RADISSON HOTEL RESTAURANT", "address": "3520 SO. FIGUEROA ST. LOS ANGELES CA 90007"],
		"VKC":
			["id": "4", "name": "VON KLEINSMID CENTER FOR INTERNATIONAL & PUBLIC AFFAIRS", "address": "3518 TROUSDALE PARKWAY LOS ANGELES CA 90089"],
		"HJF":
			["id": "510", "name": "HOWARD JONES FOOTBALL PRACTICE FIELD", "address": "3515 MCCLINTOCK AVENUE LOS ANGELES CA 90089"],
		"BKF":
			["id": "501", "name": "BRIAN KENNEDY FIELD", "address": "3515 MCCLINTOCK AVE. LOS ANGELES CA 90089"],
		"ZMT":
			["id": "237", "name": "ZONE MANAGEMENT TRAILER", "address": "3510 S. VERMONT LOS ANGELES CA 90089"],
		"NCT":
			["id": "76", "name": "EILEEN L. NORRIS CINEMA THEATRE", "address": "3507 TROUSDALE PARKWAY LOS ANGELES CA 90089"],
		"BIM":
			["id": "506", "name": "BRITTINGHAM INTRAMURAL FIELD", "address": "3506 MC CLINTOCK AVE. LOS ANGELES CA 90089"],
		"ASC":
			["id": "32", "name": "ANNENBERG SCHOOL FOR COMMUNICATION", "address": "3502 WATT WAY LOS ANGELES CA 90089"],
		"SOS":
			["id": "3.1", "name": "SOCIAL SCIENCES BUILDING", "address": "3502 TROUSDALE PARKWAY LOS ANGELES CA 90089"],
		"HER":
			["id": "16", "name": "HERITAGE HALL", "address": "3501 WATT WAY LOS ANGELES CA 90089"],
		"THH":
			["id": "35", "name": "MARK TAPER HALL OF HUMANITIES", "address": "3501 TROUSDALE PARKWAY LOS ANGELES CA 90089"],
		"MNS":
			["id": "334", "name": "MERLE NORMAN STADIUM", "address": "3501 S. FIGUEROA STREET LOS ANGELES CA 90089"],
		"BIT":
			["id": "84", "name": "BING THEATRE", "address": "3500 WATT WAY LOS ANGELES CA 90089"],
		"DMV":
			["id": "258", "name": "DEPARTMENT OF MOTOR VEHICLES", "address": "3500 SO HOPE ST. LOS ANGELES CA 90007"],
		"TMY":
			["id": "258.1", "name": "TRANSPORTATION SERVICES MAINTENANCE YARD", "address": "3500 S. HOPE ST. LOS ANGELES CA 90007"],
		"UGB":
			["id": "267", "name": "UNIVERSITY GARDENS BUILDING", "address": "3500 FIGUEROA ST. LOS ANGELES CA 90007"],
		"WPH":
			["id": "3", "name": "WAITE PHILLIPS HALL OF EDUCATION", "address": "3470 TROUSDALE PARKWAY LOS ANGELES CA 90089"],
		"SCI":
			["id": "328", "name": "SCHOOL OF CINEMATIC ARTS BUILDING \"I\".", "address": "3470 MC CLINTOCK LOS ANGELES CA 90089"],
		"CAS":
			["id": "15", "name": "COLLEGE ACADEMIC SERVICES BUILDING", "address": "3454 TROUSDALE PARKWAY LOS ANGELES CA 90089"],
		"TMC":
			["id": "220", "name": "THE MUSIC COMPLEX", "address": "3450 WATT WAY LOS ANGELES CA 90089"],
		"AES":
			["id": "223", "name": "ALICE AND ELEONORE SCHOENFELD SYMPHONIC HALL", "address": "3450 WATT WAY LOS ANGELES CA 90089"],
		"JWS":
			["id": "222", "name": "JOHN WILLIAMS SCORING STAGE", "address": "3450 WATT WAY LOS ANGELES CA 90089"],
		"CTV":
			["id": "224", "name": "CARSON TELEVISION CENTER", "address": "3450 WATT WAY LOS ANGELES CA 90089"],
		"CTC":
			["id": "221.1", "name": "CINEMA TELEVISION CENTER COMPLEX", "address": "3450 WATT WAY LOS ANGELES CA 90089"],
		"FRR":
			["id": "318", "name": "FACILITIES RESTROOM", "address": "3450 S. VERMONT AVE. LOS ANGELES CA 90089"],
		"FPM":
			["id": "259", "name": "FACILITIES PLANNING & MANAGEMENT TRAILER", "address": "3450 S. VERMONT AVE LOS ANGELES CA 90089"],
		"FTT":
			["id": "317", "name": "FACILITIES TRAILER TWO", "address": "3450 S. VERMONT AVE LOS ANGELES CA 90007"],
		"ELB":
			["id": "163", "name": "EAST LIBRARY BUILDING", "address": "3440 SOUTH HOPE ST. LOS ANGELES CA 90007"],
		"CLV":
			["id": "408", "name": "CAROLE LITTLE TELEPHONE VAULT", "address": "3434 S. GRAND AVE. LOS ANGELES CA 90007"],
		"CAL":
			["id": "281", "name": "CAROLE LITTLE BUILDING", "address": "3434 S. GRAND AVE. LOS ANGELES CA 90007"],
		"CDF":
			["id": "316", "name": "CAMPUS DEVELOPMENT & FACILITIES BUILDING", "address": "3434 GRAND AVE. LOS ANGELES CA 90007"],
		"TRF":
			["id": "330", "name": "TEMPORARY RESEARCH FACILITY-DORNSIFE", "address": "3430 S. VERMONT LOS ANGELES CA 90089"],
		"DCC":
			["id": "87", "name": "CHARLOTTE S. & DAVRE R. DAVIDSON CONTINUING EDUCATION CONFERENCE CENTER", "address": "3415 SOUTH FIGUEROA ST. LOS ANGELES CA 90089"],
		"UPX":
			["id": "199", "name": "UNIVERSITY PARKING CENTER", "address": "3401 GRAND AVE. LOS ANGELES CA 90007"],
		"GAP":
			["id": "236", "name": "GALEN ATHLETIC PAVILION", "address": "3400 S. FIGUEROA STREET LOS ANGELES CA 90089"],
		"GTT":
			["id": "409", "name": "GALEN CENTER TILLY TOWER", "address": "3400 S. FIGUEROA STREET LOS ANGELES CA 90089"],
		"GEC":
			["id": "289", "name": "GALEN EVENT CENTER", "address": "3400 S. FIGUEROA ST. LOS ANGELES CA 90089"],
		"UVI":
			["id": "268", "name": "UNIVERSITY VILLAGE", "address": "3375 S. HOOVER ST. LOS ANGELES CA 90007"],
		"UGW":
			["id": "727", "name": "UNIVERSITY GATEWAY", "address": "3335 S. FIGUEROA ST LOS ANGELES CA 90007"],
		"SCP":
			["id": "634", "name": "SOUTH COAST PLAZA BUILDING-BOOKSTORE", "address": "3333 BRISTOL ST. COSTA MESA CA 92626"],
		"FSP":
			["id": "684", "name": "FACULTY/STAFF PRACTICE", "address": "333 S. HOPE ST. STE C-145 LOS ANGELES CA 90071"],
		"UVE":
			["id": "348", "name": "UNIVERSITY VILLAGE EIGHT", "address": "3201 S. HOOVER STREET LOS ANGELES CA 90007"],
		"RZC":
			["id": "197", "name": "ROBERT ZEMECKIS CENTER FOR DIGITAL ARTS", "address": "3131 SOUTH FIGUEROA ST. LOS ANGELES CA 90007"],
		"UVN":
			["id": "349", "name": "UNIVERSITY VILLAGE NINE", "address": "3131 S. HOOVER STREET LOS ANGELES CA 90007"],
		"CAR":
			["id": "175", "name": "CARDINAL GARDENS", "address": "3131 MCCLINTOCK AVE. LOS ANGELES CA 90007"],
		"CAP":
			["id": "98", "name": "CENTURY APARTMENTS", "address": "3115 SOUTH ORCHARD AVE. LOS ANGELES CA 90007"],
		"UVF":
			["id": "344", "name": "UNIVERSITY VILLAGE FOUR", "address": "3096 MCCLINTOCK AVENUE LOS ANGELES CA 90007"],
		"HUC":
			["id": "645", "name": "HEBREW UNION COLLEGE", "address": "3077 UNIVERSITY AVENUE LOS ANGELES CA 90007"],
		"RYL":
			["id": "243", "name": "ROYAL STREET", "address": "3042 & 3042 1/2 ROYAL ST. LOS ANGELES CA 90007"],
		"PIA":
			["id": "720", "name": "PISA-SERVICAED BY ITS", "address": "3039 SHRINE PLACE LOS ANGELES CA 90007"],
		"BUN":
			["id": "716", "name": "THE BUNGALOWS-SERVISED BY ITS", "address": "3036-3046 SHRINE PLACE LOS ANGELES CA 90007"],
		"CHE":
			["id": "717", "name": "CHEZ RONNE-SERVICED BY ITS", "address": "3030 SHRINE PLACE LOS ANGELES CA 90007"],
		"ROM":
			["id": "721", "name": "ROMA-SERVICED BY ITS", "address": "3025 SHRINE PLACE LOS ANGELES CA 90007"],
		"TRH":
			["id": "176", "name": "TROY HALL", "address": "3025 ROYAL ST. LOS ANGELES CA 90007"],
		"RYT":
			["id": "651", "name": "ROYAL STREET HOUSE II", "address": "3024-3026 ROYAL ST. LOS ANGELES CA 90007"],
		"MES":
			["id": "725", "name": "JOHN MACK ELEMENTARY SCHOOL", "address": "3020 CATALINA STREET LOS ANGELES CA 90007"],
		"RYO":
			["id": "650", "name": "ROYAL STREET HOUSE I", "address": "3018 ROYAL STREET LOS ANGELES CA 90007"],
		"SPA":
			["id": "231", "name": "SHRINE PLACE APARTMENTS", "address": "3015-3017 SHRINE PL. LOS ANGELES CA 90007"],
		"UVO":
			["id": "341", "name": "UNIVERSITY VILLAGE ONE", "address": "3015 S. HOOVER STREET LOS ANGELES CA 90007"],
		"ROY":
			["id": "239", "name": "ROYAL STREET HOUSE", "address": "3014 ROYAL ST. LOS ANGELES CA 90007"],
		"IFT":
			["id": "656", "name": "ICKOVICS FAMILY TRUST BUILDING", "address": "3001 S. FLOWER ST. LOS ANGELES CA 90007"],
		"SMF":
			["id": "509", "name": "SONI MCALISTER FIELD", "address": "3000 SOUTH HOOVER ST. LOS ANGELES CA 90007"],
		"CPB":
			["id": "688", "name": "CALIFORNIA PLAZA BUILDING", "address": "300 S. GRAND AVE. LOS ANGELES CA 90011"],
		"VFS":
			["id": "782", "name": "VITERBI FLOWER STREET BUILDING", "address": "2917 S. FLOWER STREET LOS ANGELES CA 90007"],
		"CKB":
			["id": "706", "name": "COUNTY KIDS BUILDING-ECE", "address": "2916 S. HOPE STREET LOS ANGELES CA 90089"],
		"AGO":
			["id": "226", "name": "GAMMA EPSILOM OMEGA", "address": "2831 UNIVERSITY AVE. LOS ANGELES CA 90007"],
		"HSR":
			["id": "320", "name": "HOOVER STREET RESIDENCE", "address": "2827 HOOVER STREET LOS ANGELES CA 90007"],
		"ABM":
			["id": "678", "name": "AMERICAN BUTTON MANUFACTURING", "address": "2823 S. FLOWER STREET LOS ANGELES CA 90007"],
		"TSA":
			["id": "187", "name": "TERRACE APARTMENTS", "address": "2822-2830 ELLENDALE ST. LOS ANGELES CA 90007"],
		"FMH":
			["id": "264", "name": "FORTHMANN HOUSE", "address": "2801 SOUTH HOOVER ST. LOS ANGELES CA 90007"],
		"JMA":
			["id": "172", "name": "JEWEL MANOR APARTMENT", "address": "2801 ORCHARD AVE. LOS ANGELES CA 90007"],
		"STB":
			["id": "783", "name": "SHAOULIAN FAMILY TRUST BUILDING", "address": "2727 S. FLOWER ST. LOS ANGELES CA 90007"],
		"GEX":
			["id": "171.1", "name": "MAX KADE CENTER 2", "address": "2718 SO. HOOVER STREET LOS ANGELES CA 90007"],
		"ABX":
			["id": "11", "name": "ANA BING ARNOLD CHILD CARE CENTER ANNEX", "address": "2716 SEVERANCE STREET LOS ANGELES CA 90007"],
		"SSH":
			["id": "234", "name": "SEVERANCE STREET HOUSE", "address": "2716 SEVERANCE ST. LOS ANGELES CA 90007"],
		"ABA":
			["id": "113", "name": "ANNA BING ARNOLD CHILD CARE CENTER", "address": "2715 UNIVERSITY AVE. LOS ANGELES CA 90007"],
		"GEH":
			["id": "171", "name": "MAX KADE CENTER 1", "address": "2714 S. HOOVER STREET LOS ANGELES CA 90007"],
		"BTP":
			["id": "152", "name": "BETA THETA PI FRATERNITY", "address": "2714 PORTLAND AVE. LOS ANGELES CA 90007"],
		"HHR":
			["id": "160", "name": "HONOR'S HOUSE RESIDENCE", "address": "2710 SEVERANCE ST. LOS ANGELES CA 90007"],
		"VIS":
			["id": "240", "name": "VISTA APARTMENTS", "address": "2701 SEVERANCE ST. LOS ANGELES CA 90007"],
		"COH":
			["id": "265", "name": "COCKINS HOUSE", "address": "2653 S. HOOVER ST. LOS ANGELES CA 90007"],
		"SIE":
			["id": "186", "name": "SIERRA APARTMENTS", "address": "2638 PORTLAND ST. LOS ANGELES CA 90007"],
		"PCA":
			["id": "188", "name": "PACIFIC APARTMENTS", "address": "2637 SEVERANCE ST. LOS ANGELES CA 90007"],
		"MAB":
			["id": "194", "name": "MANOR APARTMENTS", "address": "2636 PORTLAND ST. LOS ANGELES CA 90007"],
		"TPA":
			["id": "173", "name": "TWIN PALMS APARTMENTS", "address": "2635 PORTLAND ST. LOS ANGELES CA 90007"],
		"SSA":
			["id": "654", "name": "SEVERANCE STREET APARTMENTS", "address": "2630 SEVERANCE ST. LOS ANGELES CA 90007"],
		"FMT":
			["id": "168", "name": "FAIRMONT APARTMENT", "address": "2629 PORTLAND AVE. LOS ANGELES CA 90007"],
		"FSA":
			["id": "179", "name": "FOUNDERS APARTMENTS", "address": "2610 PORTLAND AVE. LOS ANGELES CA 90007"],
		"HIL":
			["id": "178", "name": "HILLVIEW APARTMENTS", "address": "2605 SEVERANCE ST. LOS ANGELES CA 90007"],
		"BTL":
			["id": "644", "name": "BEHAVIOR TECHNOLOGY LABS", "address": "250 N. HARBOR DRIVE REDONDO BCH CA 90278"],
		"RHC":
			["id": "694", "name": "EDWARD R. ROYAL COMPREHENSIVE HEALTH CENTER", "address": "245 S. FETTERLY AVE. EAST LOS ANGELES CA 90022"],
		"ORH":
			["id": "628", "name": "ORTHOPEDIC HOSPITAL", "address": "2400 SOUTH FLOWER ST. LOS ANGELES CA 90007"],
		"CEN":
			["id": "184", "name": "CENTENNIAL APARTMENTS", "address": "2390 PORTLAND AVE. LOS ANGELES CA 90007"],
		"SVB":
			["id": "675", "name": "ST. VINCENTS CENTER BUILDING", "address": "2335 S. FIGUEROA ST. LOS ANGELES CA 90007"],
		"UNA":
			["id": "664", "name": "UNION AVENUE BUILDING", "address": "2310,2312,2314 UNION AVE LOS ANGELES CA 90007"],
		"TRC":
			["id": "643", "name": "TRC - USC KIDNEY CENTER", "address": "2310 ALCAZAR STREET LOS ANGELES CA 90033"],
		"OCC":
			["id": "284", "name": "ORANGE COUNTY CAMPUS", "address": "2300 MICHELSON DR. IRVINE CA 92714"],
		"NMA":
			["id": "708", "name": "NORTH MARYLAND AVENUE BUILDING", "address": "230 N. MARYLAND AVE. GLENDALE CA 91206"],
		"CSA":
			["id": "249", "name": "CLINICAL SCIENCES ANNEX", "address": "2250 ALCAZAR ST. LOS ANGELES CA 90033"],
		"CSC":
			["id": "247", "name": "CLINICAL SCIENCE CENTER", "address": "2250 ALCAZAR ST. LOS ANGELES CA 90033"],
		"CCC":
			["id": "12", "name": "HEALTH SCIENCE CAMPUS CHILD CARE CENTER", "address": "2250 ALCAZAR ST LOS ANGELES CA 90033"],
		"VEC":
			["id": "673", "name": "VILLA ESPERANZA CENTER BUILDING", "address": "225 E. 28TH STREETE LOS ANGELES CA 90011"],
		"CHD":
			["id": "778", "name": "CURRIE HALL - DAYCARE", "address": "2215 E. ALCAZAR STREET LOS ANGELES CA 90033"],
		"HC3":
			["id": "335", "name": "NORRIS HEALTHCARE CONSULTATION CENTER", "address": "2204 ALCAZAR STREET LOS ANGELES CA 90033"],
		"PST":
			["id": "238", "name": "PUBLIC SAFETY TRAILER", "address": "2200 LAMBIE STREET LOS ANGELES CA 90033"],
		"MRI":
			["id": "353", "name": "MAGNETIC RESONANCE IMAGING BUILDING", "address": "2025 ZONAL AVE. LOS ANGELES CA 90033"],
		"SHN":
			["id": "67", "name": "STEVENS HALL NEUROIMAGING (FORMERLY RMR).", "address": "2025 ZONAL AVE. LOS ANGELES CA 90033"],
		"IRD":
			["id": "631", "name": "INTERNS & RESIDENTS DORMITORY", "address": "2020 ZONAL AVE. LOS ANGELES CA 90033"],
		"HMR":
			["id": "22", "name": "ELAINE STEVELY HOFFMAN MEDICAL RESEARCH CENTER", "address": "2011 ZONAL AVE. LOS ANGELES CA 90033"],
		"SST":
			["id": "333", "name": "SOTO STREET BUILDING TWO", "address": "2011 SOTO STREET LOS ANGELES CA 90033"],
		"NML":
			["id": "69", "name": "NORRIS MEDICAL LIBRARY", "address": "2003 ZONAL AVE. LOS ANGELES CA 90033"],
		"SSB":
			["id": "235", "name": "SOTO STREET BUILDING", "address": "2001 N. SOTO STREET LOS ANGELES CA 90032"],
		"SBA":
			["id": "329", "name": "SOTO STREET BUILDING ANNEX", "address": "2001 N. SOTO STREET LOS ANGELES CA 90032"],
		"BAR":
			["id": "607", "name": "BARLOW HOSPITAL", "address": "2000 STADIUM WAY LOS ANGELES CA 90026"],
		"EVH":
			["id": "406", "name": "HEALTH SCIENCE DWP ELECTRICAL VAULT", "address": "2000 EASTLAKE AVE. LOS ANGELES CA 90033"],
		"PSC":
			["id": "71", "name": "JOHN STAUFFER PHARMACEUTICAL SCIENCES CENTER", "address": "1985 ZONAL AVE. LOS ANGELES CA 90033"],
		"KAM":
			["id": "70", "name": "WILLARD KEITH ADMINISTRATION & MEDICAL FORUM BUILDING; LOUIS B. MAYER MEDICAL TEACHING CENTER", "address": "1975 ZONAL AVE. LOS ANGELES CA 90033"],
		"SRH":
			["id": "147", "name": "BLANCHE & FRANK R. SEAVER STUDENT RESIDENCE HALL", "address": "1969 ZONAL AVE. LOS ANGELES CA 90033"],
		"FRE":
			["id": "351", "name": "FREEMAN HOUSE", "address": "1962 GLENCOE WAY LOS ANGELES CA 90068"],
		"EHP":
			["id": "681", "name": "ESTRELLA HOUSING PARTNERS", "address": "1953 ESTRELLA AVE. LOS ANGELES CA 90007"],
		"GRH":
			["id": "612", "name": "GRADUATE HALL", "address": "1937 HOSPITAL PLACE LOS ANGELES CA 90031"],
		"GNH":
			["id": "603", "name": "COUNTY GENERAL HOSPITAL", "address": "1937 HOSPITAL PLACE LOS ANGELES CA 90031"],
		"CLB":
			["id": "615", "name": "CLINICAL ADMINISTRATION BUILDING", "address": "1927 ZONAL AVENUE LOS ANGELES CA 90033"],
		"EDM":
			["id": "96", "name": "DOROTHY & HUGH EDMONDSON RESEARCH BUILDING", "address": "1840 NORTH SOTO STREET LOS ANGELES CA 90033"],
		"VHH":
			["id": "337", "name": "VERDUGO HILLS HOSPITAL", "address": "1812 VERDUGO BLVD. GLENDALE CA 91208"],
		"SAC":
			["id": "270", "name": "SACRAMENTO CENTER", "address": "1800 I STREET SACRAMENTO CA 95814"],
		"PHH":
			["id": "620", "name": "PHINNEY HALL", "address": "1721 GRIFFIN AVE. LOS ANGELES CA 90033"],
		"TOW":
			["id": "622", "name": "TOWER HALL", "address": "1711 NORTH GRIFFIN AVE. LOS ANGELES CA 90033"],
		"BDB":
			["id": "714", "name": "BERNARDO DRIVE BUILDING-SOSW", "address": "16870 W. BERNARDO DR. 200 SAN DIEGO CA 92127"],
		"TCD":
			["id": "709", "name": "TROJAN CHILD DEVELOPMENT CENTER", "address": "1664-66 W. ADAMS BLVD. LOS ANGELES CA 90007"],
		"HRA":
			["id": "605", "name": "HEALTH RESEARCH ASSOCIATION", "address": "1640 MARENGO STREET LOS ANGELES CA 90033"],
		"CPL":
			["id": "916", "name": "CONSOLIDATED PARKING LOT", "address": "1633 NORTH SAN PABLO ST. LOS ANGELES CA 90033"],
		"SSP":
			["id": "915", "name": "SAN PABLO SURFACE PARKING LOT", "address": "1630 SAN PABLO ST. LOS ANGELES CA 90033"],
		"SPS":
			["id": "354", "name": "SAN PABLO PARKING STRUCTURE", "address": "1630 N. SAN PABLO ST. LOS ANGELES CA 90033"],
		"UPH":
			["id": "86", "name": "UNIVERSITY PRESIDENT'S HOME", "address": "1550 OAK GROVE AVE. SAN MARINO CA 91108"],
		"CHP":
			["id": "255", "name": "CENTER FOR HEALTH PROFESSIONS", "address": "1540 ALCAZAR STREET LOS ANGELES CA 90033"],
		"UHP":
			["id": "642", "name": "UNIVERSITY HOSPITAL PARKING BLDG.", "address": "1538 SAN PABLO ST. LOS ANGELES CA 90033"],
		"HC4":
			["id": "610", "name": "ESTELLE DOHENY EYE INSTITUTE", "address": "1537 NORFOLK ST. LOS ANGELES CA 90033"],
		"HSV":
			["id": "403", "name": "HEALTH SCIENCE TELEPHONE VAULT", "address": "1521 SAN PABLO ST. LOS ANGELES CA 90033"],
		"HC2":
			["id": "287", "name": "HEALTHCARE CONSULTATION CENTER II", "address": "1520 SAN PABLO ST. LOS ANGELES CA 90033"],
		"HC1":
			["id": "269", "name": "SC HEALTHCARE CONSULTATION CENTER", "address": "1510 SAN PABLO ST. LOS ANGELES CA 90033"],
		"ZNI":
			["id": "282", "name": "ZILKHA NEUROGENETIC INSTITUTE", "address": "1501 SAN PABLO ST. LOS ANGELES CA 90033"],
		"OPL":
			["id": "917", "name": "O'NEAL PARKING LOT", "address": "1501 N. SOTO ST. LOS ANGELES CA 90033"],
		"UNH":
			["id": "640", "name": "USC UNIVERSITY HOSPITAL", "address": "1500 SAN PABLO ST. LOS ANGELES CA 90033"],
		"NRT":
			["id": "288", "name": "HARLYNE J. NORRIS RESEARCH TOWER", "address": "1450 BIGGY STREET LOS ANGELES CA 90033"],
		"PGV":
			["id": "655", "name": "PLAYGROUND HOUSE V", "address": "1448 PLAYGROUND ST. LOS ANGELES CA 90033"],
		"NTT":
			["id": "17", "name": "DOCTOR NORMAN TOPPING TOWER", "address": "1441 EASTLAKE AVENUE LOS ANGELES CA 90033"],
		"NOR":
			["id": "81", "name": "KENNETH NORRIS JR. CANCER HOSPITAL RESEARCH INSTITUTE", "address": "1441 EASTLAKE AVE. LOS ANGELES CA 90033"],
		"PGH":
			["id": "338", "name": "PLAYGROUND HOUSE", "address": "1433 PLAYGROUND LOS ANGELES CA 90033"],
		"PGF":
			["id": "659", "name": "PLAYGROUND HOUSE IV", "address": "1429 PLAYGROUND ST. LOS ANGELES CA 90033"],
		"BCC":
			["id": "266", "name": "ELI & EDYTH BROAD CIRM CENTER FOR REGENERATIVE MEDICINE & STEM CELL RESCH.", "address": "1425 SAN PABLO ST. LOS ANGELES CA 90033"],
		"PAV":
			["id": "698", "name": "PLAYGROUND AVENUE HOUSE", "address": "1420 PLAYGROUND AVE. LOS ANGELES CA 90033"],
		"PGD":
			["id": "657", "name": "PLAYGROUND DUPLEX", "address": "1417-1419 PLAYGROUND ST. LOS ANGELES CA 90033"],
		"CAH":
			["id": "625", "name": "CALIFORNIA HOSPITAL", "address": "1414 SOUTH HOPE ST. LOS ANGELES CA 90015"],
		"PGT":
			["id": "658", "name": "PLAYGROUND HOUSE III", "address": "1409 PLAYGROUND ST. LOS ANGELES CA 90033"],
		"DOH":
			["id": "609", "name": "ESTELLE DOHENY EYE FOUNDATION", "address": "1355 SAN PABLO ST. LOS ANGELES CA 90033"],
		"HSP":
			["id": "190", "name": "HEALTH SCIENCES CAMPUS PARKING STRUCTURE", "address": "1334 BIGGY ST. LOS ANGELES CA 90033"],
		"CRB":
			["id": "674", "name": "LOS ANGELES CAREGIVER RESOURCE CENTER-BALDWIN PARK", "address": "13334 RAMONA BLVD. UNIT J IRWINDALE CA 91706"],
		"MCH":
			["id": "108.1", "name": "MCKIBBEN HALL", "address": "1333 SAN PABLO ST. LOS ANGELES CA 90033"],
		"MCA":
			["id": "108.6", "name": "MCKIBBEN ADDITION", "address": "1333 SAN PABLO ST. LOS ANGELES CA 90033"],
		"MMR":
			["id": "108", "name": "MUDD MEMORIAL RESEARCH BUILDING", "address": "1333 SAN PABLO ST. LOS ANGELES CA 90033"],
		"BMT":
			["id": "68", "name": "JOHN E. BISHOP MEDICAL TEACHING & RESEARCH BUILDING", "address": "1333 SAN PABLO ST. LOS ANGELES CA 90033"],
		"ICT":
			["id": "668", "name": "INSTITUTE FOR CREATIVE TECHNOLOGIES", "address": "13274 FIJI WAY MARINA DEL REY CA 90292"],
		"LRB":
			["id": "617", "name": "LIVINGSTON RESEARCH BUILDING", "address": "1321 NORTH MISSION ROAD LOS ANGELES CA 90033"],
		"LRA":
			["id": "660", "name": "LIVINGSTON RESEARCH ANNEX", "address": "1321 NORTH MISSION ROAD LOS ANGELES CA 90033"],
		"MVA":
			["id": "670", "name": "MONTE VISTA AVENUE", "address": "1306 MONTE VISTA AVE. #7 CLAREMONT CA 91711"],
		"CRL":
			["id": "608", "name": "CANCER RESEARCH LABORATORY", "address": "1303 MISSION ROAD. LOS ANGELES CA 90033"],
		"HPH":
			["id": "614", "name": "HOLLYWOOD PRESBYTERIAN HOSPITAL", "address": "1300 NORTH VERMONT AVE. LOS ANGELES CA 90027"],
		"RSC":
			["id": "632", "name": "RAND SCHRADER OUTPATIENT CLINIC", "address": "1300 MISSION AVE. LOS ANGELES CA 90033"],
		"SMC":
			["id": "325", "name": "SANTA MONICA CONDO-SEA COLONY", "address": "130 OCEAN PARK BLVD. SANTA MONICA CA 90405"],
		"GTL":
			["id": "711", "name": "GREATER TRUE LIGHT BUILDING-ECE", "address": "1276 W. 29TH STREET LOS ANGELES CA 90007"],
		"CBG":
			["id": "669", "name": "CBG-UNIVERSITY GARDENS APTS.", "address": "1250 W. JEFFERSON BLVD. LOS ANGELES CA 90007"],
		"PIH":
			["id": "621", "name": "PRESBYTERIAN INTERCOMMUNITY HOSPITAL", "address": "12401 EAST WASHINGTON BLVD WHITTIER CA 90602"],
		"WOH":
			["id": "624", "name": "WOMENS HOSPITAL", "address": "1240 NORTH MISSION LOS ANGELES CA 90033"],
		"MOL":
			["id": "618", "name": "MEDICAL ONCOLOGY LAB", "address": "1237 NORTH MISSION ROAD LOS ANGELES CA 90033"],
		"HAP":
			["id": "181", "name": "HELENA APARTMENTS", "address": "1220 WEST 28TH ST. LOS ANGELES CA 90007"],
		"URA":
			["id": "177", "name": "UNIVERSITY REGENT APARTMENT", "address": "1219 WEST 27TH ST. LOS ANGELES CA 90007"],
		"PVB":
			["id": "730", "name": "PLAYA VISTA BUILDING", "address": "12015 E. WATERFRONT DRIVE PLAYA VISTA CA 90094"],
		"BAB":
			["id": "602", "name": "BARRACKS A & B", "address": "1200 NORTH STATE ST. LOS ANGELES CA 90031"],
		"OPD":
			["id": "619", "name": "OUTPATIENT DEPARTMENT", "address": "1175 NORTH CUMMINGS ST. LOS ANGELES CA 90033"],
		"LAB":
			["id": "229", "name": "LA SORBONNE APARTMENTS", "address": "1170 WEST 31ST ST. LOS ANGELES CA 90007"],
		"EVO":
			["id": "324", "name": "EVO CONDOMINIUM", "address": "1155 S. GRAND AVE. #1410 LOS ANGELES CA 90015"],
		"GEE":
			["id": "908", "name": "GATE #8 ENTRANCE-PARKING LOT 1", "address": "1150 W. JEFFERSON BLVD. LOS ANGELES CA 90089"],
		"SCT":
			["id": "726", "name": "USC BUILDING TWO (FORMERLY ATB)", "address": "1150 S. OLIVE STREET LOS ANGELES CA 90015"],
		"LMJ":
			["id": "693", "name": "LORRAINE AND MARVIN JACOBS BUILDING.", "address": "1150 S. HOPE ST., UNIT-B LOS ANGELES CA 90015"],
		"WIN":
			["id": "244", "name": "WINDSOR APARTMENTS", "address": "1149 WEST 28TH ST. LOS ANGELES CA 90007"],
		"SCO":
			["id": "704", "name": "USC BUILDING ONE (FORMERLY ATT)", "address": "1149 S. HILL STREET LOS ANGELES CA 90015"],
		"ACD":
			["id": "723", "name": "ANNENBERG CENTER FOR DIGITAL FUTURES", "address": "11444 W. OLYMPIC BL. #120 LOS ANGELES CA 90064"],
		"SUN":
			["id": "245", "name": "SUNSET APARTMENTS", "address": "1144 WEST 29TH ST. LOS ANGELES CA 90007"],
		"RGA":
			["id": "241.1", "name": "REGENT APARTMENTS", "address": "1138 WEST 29TH ST. LOS ANGELES CA 90007"],
		"GLB":
			["id": "611", "name": "GENERAL LABS. BLDG", "address": "1129 NORTH STATE ST. LOS ANGELES CA 90033"],
		"BAA":
			["id": "241", "name": "BELAIRE APARTMENTS", "address": "1124 WEST 29TH ST. LOS ANGELES CA 90007"],
		"SHE":
			["id": "662", "name": "ST. HELENA EDUCATION-ROSSIER SCHOOL OF EDUCATION", "address": "1120 POPE ST. SUITE 201-C ,"],
		"SNA":
			["id": "227", "name": "SENATOR APARTMENTS", "address": "1101-1109 28TH ST LOS ANGELES CA 90007"],
		"LBP":
			["id": "692", "name": "LA BREA POLE BUILDING", "address": "110 S. LA BREA INGLEWOOD CA 90301"],
		"MTX":
			["id": "505", "name": "MARKS TENNIS STADIUM (COURT AREA)", "address": "1075 CHILDS WAY LOS ANGELES CA 90089"],
		"MTS":
			["id": "93", "name": "DAVID X. MARKS TENNIS STADIUM", "address": "1075 CHILDS WAY LOS ANGELES CA 90089"],
		"RRI":
			["id": "291", "name": "RAY R. IRANI HALL", "address": "1050 CHILDS WAY LOS ANGELES CA 90089"],
		"DRB":
			["id": "111", "name": "CORWIN D. DENNEY RESEARCH CENTER", "address": "1042 DOWNEY WAY LOS ANGELES CA 90089"],
		"APS":
			["id": "676", "name": "ARCHITECTURE-POWER STATION", "address": "1037 W. 24TH STREET LOS ANGELES CA 90007"],
		"ESH":
			["id": "326", "name": "ROGER AND MICHELE DEDEAUX ENGEMANN STUDENT HEALTH CENTER.", "address": "1031 W. 34TH STREET LOS ANGELES CA 90089"],
		"SCD":
			["id": "20", "name": "SCENE DOCK THEATRE", "address": "1030 WEST 37TH ST. LOS ANGELES CA 90089"],
		"DRC":
			["id": "79", "name": "DRAMA CENTER", "address": "1029-33 CHILDS WAY LOS ANGELES CA 90089"],
		"FLT":
			["id": "56", "name": "FLUOR TOWER", "address": "1027 WEST 34TH ST. LOS ANGELES CA 90089"],
		"LRC":
			["id": "250", "name": "GENERAL WILLIAM LYON UNIVERSITY CENTER", "address": "1026 WEST 34TH STREET LOS ANGELES CA 90089"],
		"UAC":
			["id": "332", "name": "UYTENGSU AQUATICS CENTER", "address": "1026 W. 34TH STREET LOS ANGELES CA 90089"],
		"KOH":
			["id": "228", "name": "FRANK L. KING OLYMPIC HALL OF CHAMPIONS", "address": "1025 WEST 34TH ST. LOS ANGELES CA 90089"],
		"GPC":
			["id": "511", "name": "GOLF PRACTICE COURSE", "address": "1021 CHILDS WAY LOS ANGELES CA 90089"],
		"BDF":
			["id": "73", "name": "JOHN G. BROOKS MEMORIAL PAVILION & DEDEAUX FIELD", "address": "1021 CHILDS WAY LOS ANGELES CA 90089"],
		"BDX":
			["id": "502", "name": "DEDEAUX FIELD", "address": "1021 CHILDS WAY LOS ANGELES CA 90089"],
		"TTL":
			["id": "296", "name": "TECHNICAL THEATRE LABORATORY", "address": "1020 BLOOM WALK LOS ANGELES CA 90089"],
		"USD":
			["id": "775", "name": "USC NUEROLOGY AT SAN DIEGO", "address": "10182 TELESIS COURT SAN DIEGO CA 92121"],
		"WTO":
			["id": "55", "name": "WEBB TOWER", "address": "1015 WEST 34TH ST. LOS ANGELES CA 90089"],
		"TCX":
			["id": "508", "name": "TENNIS COURT I", "address": "1015 CHILDS WAY LOS ANGELES CA 90089"],
		"GSE":
			["id": "907", "name": "GATE #7 ENTRANCE-PARKING LOT 1", "address": "1015 CHILDS WAY LOS ANGELES CA 90089"],
		"CWT":
			["id": "59", "name": "CHILDS WAY BUILDING 2", "address": "1014 CHILDS WAY LOS ANGELES CA 90089"],
		"MCE":
			["id": "905", "name": "MCCLINTOCK AVE. ENTRANCE-GATE #5", "address": "1010 W. JEFFERSON BLVD. LOS ANGELES CA 90089"],
		"MCC":
			["id": "25", "name": "MCCLINTOCK BUILDING", "address": "1010 W. JEFFERSON BLVD. LOS ANGELES CA 90089"],
		"MCB":
			["id": "350", "name": "MICHELSON CENTER FOR CONVERGENT BIOSCIENCE", "address": "1002 CHILDS WAY LOS ANGELES CA 90089"],
		"WDC":
			["id": "701", "name": "WASHINGTON, DC BUILDING-UNIVERSITY RELATIONS", "address": "1000 S. VERMONT AVE. WASHINGTON DC 20005"],
		"HSA":
			["id": "635", "name": "HEALTH SCIENCE ALHAMBRA BUILDING", "address": "1000 S. FREMONT AVE. ALHAMBRA CA 91803"],
		"SMB":
			["id": "724", "name": "SAN MARCOS BUILDING", "address": "100 SAN MARCOS BLVD. #437 SAN MARCOS CA 92069"],
		"HMH":
			["id": "613", "name": "HUNTINGTON MEMORIAL HOSPITAL", "address": "100 CONGRESS ST. PASADENA CA 91105"],
		"THR":
			["id": "203", "name": "TWO HARBOR RESIDENCES", "address": "1 BIG FISHERMAN COVE AVALON CA 90704"],
		"WDH":
			["id": "206", "name": "WRIGLEY EDUCATIONAL DIRECTORS HOUSE", "address": "1 BIG FISHERMAN COVE AVALON CA 90704"],
		"WIH":
			["id": "204", "name": "WRIGLEY INSTITUTE HOUSING", "address": "1 BIG FISHERMAN COVE AVALON CA 90704"],
		"BCH":
			["id": "295", "name": "BOONE CENTER HOUSING - CATALINA ISLAND", "address": "1 BIG FISHERMAN COVE AVALON CA 90704"],
		"WGH":
			["id": "213", "name": "WRIGLEY GREENHOUSE", "address": "1 BIG FISHERMAN COVE AVALON CA 90704"],
		"DLC":
			["id": "207", "name": "CMSC DIVING LOCKERS", "address": "1 BIG FISHERMAN COVE AVALON CA 90704"],
		"CAB":
			["id": "209", "name": "CMSC ADMINISTRATION BUILDING", "address": "1 BIG FISHERMAN COVE AVALON CA 90704"],
		"DLT":
			["id": "210", "name": "DIVE LOCKER TWO", "address": "1 BIG FISHERMAN COVE AVALON CA 90704"],
		"HCB":
			["id": "208", "name": "CMSC HYPERBARIC CHAMBER BLDG.", "address": "1 BIG FISHERMAN COVE AVALON CA 90704"],
		"MSC":
			["id": "200", "name": "MARINE SCIENCES CENTER LABORATORY", "address": "1 BIG FISHERMAN COVE AVALON CA 90704"],
		"MSR":
			["id": "201", "name": "MARINE SCIENCES CENTER RESIDENCE HALL", "address": "1 BIG FISHERMAN COVE AVALON CA 90704"],
		"MST":
			["id": "205", "name": "MEDICAL STAFF TRAILER", "address": "1 BIG FISHERMAN COVE AVALON CA 90704"],
		"MTT":
			["id": "202", "name": "MEDICAL TECHNICAL TRAILER", "address": "1 BIG FISHERMAN COVE AVALON CA 90704"],
		"DLO":
			["id": "211", "name": "DIVE LOCKER ONE", "address": "1 BIG FISHERMAN COVE AVALON CA 90704"],
		"PSB":
			["id": "192", "name": "PARKING STRUCTURE B", "address": "LOT 1-1150 WEST JEFFERSON BLVD"]
    ]

};
