source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '10.0'
inhibit_all_warnings!
use_frameworks!

target 'MapSC' do
    pod 'GoogleMaps'
    pod 'GooglePlacePicker' 
    pod 'GooglePlaces'
    pod 'Alamofire', '~> 4.2.0'
end
